http:
  listener:
    host: "localhost"
    port: "9082"
    path: "/FastGoCall/{serviceType}"
    
db:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "Ashok@333"
  database: "transportapi"